# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
#   By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed
#   four million, find the sum of the even-valued terms.

def even_fibonacci(max):
    n_minus_1 = 1
    n_minus_2 = 0
    while True:
        n = n_minus_1 + n_minus_2
        n_minus_2 = n_minus_1
        n_minus_1 = n

        if n > max:
            return
        if n % 2 == 0:
            yield n


if __name__ == "__main__":
    print(f'The sum of even fibonacci numbers under 4 million is {sum(even_fibonacci(4000000))}')
