name: 'Unit Tests'

on:
  workflow_dispatch:
    branches:
     - '**'

  push:
    branches:
      - '**'

jobs:
  RunUnitTests:
    runs-on: ubuntu-latest
    steps:
      # Checkout Sources
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.9
          architecture: x64

      - name: Install pytest
        run: pip install pytest

      - name: Run Tests
        run: python -m pytest
